name: CI Build Trigger
on:
  push:

jobs:
  start:
    name: Start
    runs-on: self-hosted
    environment: nova.ci
    steps:
      - name: Checkout
        uses: actions/checkout@v3

  ci-build-trigger-switcher:
    name: CI Build Trigger Switcher
    uses: novaittestteam/nova.ci/.github/workflows/ci-build-trigger-android.yaml@main
    secrets: inherit
